{ ... }:

{
  # GIt
  programs.git = {
    enable = true;
    lfs.enable = true;

    settings = {
      init.defaultBranch = "main";

      user = {
        name  = "LFour86";
        email = "lfourneen@qq.com";
      };

      # Use gh's credentials for GitHub (gh auth login already done).
      # Must be in this declarative file; ~/.config/git/config is a read-only
      # /nix/store symlink generated by home-manager.
      credential = {
        helper = "";
      };
      "credential \"https://github.com\"" = {
        helper = "!gh auth git-credential";
      };
    };
  };
}

